SELECT CUSTDFF_EDO_FLEX_STRING11   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING11 order by CUSTDFF_EDO_FLEX_STRING11 ;
SELECT CUSTDFF_EQBO_FLEX_STRING19  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING19 order by CUSTDFF_EQBO_FLEX_STRING19;
SELECT DESTINATION                 FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  DESTINATION  order by  DESTINATION  ;

SELECT CUSTDFF_EQBO_FLEX_STRING16  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY CUSTDFF_EQBO_FLEX_STRING16 order by CUSTDFF_EQBO_FLEX_STRING16 ;
SELECT CUSTDFF_EQBO_FLEX_STRING15  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING15 order by CUSTDFF_EQBO_FLEX_STRING15 ;






SELECT SUB_TYPE                    FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  SUB_TYPE                  ;
SELECT CUSTDFF_EDO_FLEX_STRING03   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING03 ;
SELECT EQ_STATUS                   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  EQ_STATUS                 ;














SELECT CUSTDFF_EQBO_FLEX_STRING14  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING14;
SELECT CUSTDFF_EQBO_FLEX_STRING13  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING13;
SELECT CUSTDFF_EDO_FLEX_STRING01   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING01;
SELECT NBR                         FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  NBR                       ;
SELECT CUSTDFF_EQBO_FLEX_STRING28  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING28;
SELECT CUSTDFF_EQBO_FLEX_STRING27  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING27;
SELECT CUSTDFF_ERO_FLEX_STRING12   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_ERO_FLEX_STRING12 ;
SELECT CUSTDFF_ERO_FLEX_STRING11   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_ERO_FLEX_STRING11 ;
SELECT CUSTDFF_EDO_FLEX_STRING24   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING24 ;
SELECT CUSTDFF_EQBO_FLEX_STRING21  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING21;
SELECT CUSTDFF_EQBO_FLEX_STRING25  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING25;
SELECT CUSTDFF_EQBO_FLEX_STRING24  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING24;
SELECT CUSTDFF_EQBO_FLEX_STRING23  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING23;
SELECT CUSTDFF_EQBO_FLEX_STRING22  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING22;
SELECT CUSTDFF_EDO_FLEX_STRING18   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING18;
SELECT CUSTDFF_EDO_FLEX_STRING20   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING20 ;
SELECT CUSTDFF_EDO_FLEX_STRING19   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING19 ;
SELECT CUSTDFF_EDO_FLEX_STRING17   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING17 ;
SELECT CUSTDFF_EDO_FLEX_STRING16   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING16 ;
SELECT CUSTDFF_EDO_FLEX_STRING23   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING23 ;
SELECT CUSTDFF_EDO_FLEX_STRING22   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING22 ;
SELECT CUSTDFF_EDO_FLEX_STRING21   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING21 ;
SELECT CUSTDFF_EDO_FLEX_STRING14   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING14 ;
SELECT CUSTDFF_EDO_FLEX_STRING12   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING12 ;

SELECT CUSTDFF_EDO_FLEX_STRING10   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING10 ;
SELECT CUSTDFF_EDO_FLEX_STRING06   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING06 ;
SELECT CUSTDFF_EDO_FLEX_STRING08   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING08 ;
SELECT CUSTDFF_EDO_FLEX_STRING13   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING13 ;
SELECT CUSTDFF_EDO_FLEX_STRING15   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING15 ;
SELECT CUSTDFF_EDO_FLEX_STRING09   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING09 ;
SELECT CUSTDFF_EDO_FLEX_STRING07   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING07 ;
SELECT CUSTDFF_EDO_FLEX_STRING05   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING05 ;
SELECT CUSTDFF_EDO_FLEX_STRING04   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING04 ;
SELECT CUSTDFF_EDO_FLEX_STRING02   FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EDO_FLEX_STRING02 ;
SELECT CUSTDFF_EQBO_FLEX_STRING12  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING12;
SELECT CUSTDFF_EQBO_FLEX_STRING11  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING11;
SELECT CUSTDFF_EQBO_FLEX_STRING10  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING10;
SELECT CUSTDFF_EQBO_FLEX_STRING09  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING09;
SELECT CUSTDFF_EQBO_FLEX_STRING08  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING08;
SELECT CUSTDFF_EQBO_FLEX_STRING07  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING07;
SELECT CUSTDFF_EQBO_FLEX_STRING06  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING06;
SELECT CUSTDFF_EQBO_FLEX_STRING20  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING20;

SELECT CUSTDFF_EQBO_FLEX_STRING18  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING18;
SELECT CUSTDFF_EQBO_FLEX_STRING17  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING17;
SELECT CATEGORY                    FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CATEGORY                  ;
SELECT FULL_RETURN_LOCATION        FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  FULL_RETURN_LOCATION      ;
SELECT STUFFING_LOCATION           FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  STUFFING_LOCATION         ;
SELECT EMPTY_PICKUP_LOCATION       FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  EMPTY_PICKUP_LOCATION     ;
SELECT MILITARY_TCN                FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  MILITARY_TCN              ;
SELECT DRAY_OFF                    FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  DRAY_OFF                  ;
SELECT SHIPPING_MODE               FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  SHIPPING_MODE             ;
SELECT STOW_BLOCK                  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  STOW_BLOCK                ;
SELECT SERVICE_TYPE                FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  SERVICE_TYPE              ;
SELECT EQ_OWNED_LEASED             FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  EQ_OWNED_LEASED           ;
SELECT DISPATCH_RESERVED           FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  DISPATCH_RESERVED         ;
SELECT NOTES                       FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  NOTES                     ;
SELECT ORIGIN                      FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  ORIGIN                    ;
SELECT CLIENT_REF_NBR              FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CLIENT_REF_NBR            ;
SELECT SHIPPER_NAME                FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  SHIPPER_NAME              ;
SELECT CONSIGNEE_NAME              FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CONSIGNEE_NAME            ;
SELECT CHANGER                     FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CHANGER                   ;
SELECT CREATOR                     FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CREATOR                   ;
SELECT CUSTDFF_EQBO_FLEX_STRING05  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING05;
SELECT CUSTDFF_EQBO_FLEX_STRING03  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING03;
SELECT CUSTDFF_EQBO_FLEX_STRING01  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING01;
SELECT CUSTDFF_EQBO_FLEX_STRING02  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING02;
SELECT CUSTDFF_EQBO_FLEX_STRING04  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING04;
SELECT CUSTDFF_EXPORTER_NAME       FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EXPORTER_NAME     ;
SELECT CUSTDFF_EXPORTER_ID         FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EXPORTER_ID       ;
SELECT CUSTDFF_LIFE_CYCLE_STATE    FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_LIFE_CYCLE_STATE  ;
SELECT CUSTDFF_MANIFEST_NBR        FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_MANIFEST_NBR      ;
SELECT CUSTDFF_EXTERNAL_SYSTEM     FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EXTERNAL_SYSTEM   ;
SELECT CUSTDFF_EQBO_FLEX_STRING26  FROM USRTOSN4P.INV_EQ_BASE_ORDER GROUP BY  CUSTDFF_EQBO_FLEX_STRING26;