SELECT
TO_CHAR(EV.PLACED_TIME,'DD/MM/YYYY') AS "FECHA ASIGNACION",
EQBO.CUSTDFF_EDO_FLEX_STRING11 AS "Tipo Reserva Depot",
TO_CHAR(VVD.PUBLISHED_ETA,'DD/MM/YYYY') AS "FECHA ETA",
EQBO.CUSTDFF_EDO_FLEX_STRING12 AS "PLEX",
EQBO.NBR AS "NÚMERO DE BOOKING",
U.ID AS "Nro Contenedor",
SUBSTR(RET.ID,1,2) as "TAMAÑO",
SUBSTR(RET.ID,3,2) as "TIPO",
BS.ID AS "Linea Naviera",
EQBO.CUSTDFF_EDO_FLEX_STRING04 AS "NUMERO DE INTEGRAL",
EQBO.CUSTDFF_EDO_FLEX_STRING05 AS "CLIENTE",
EQBO.CUSTDFF_EDO_FLEX_STRING13 AS "OPERADOR LOGISTICO",
BSA.NAME AS "AGENTE DE ADUANAS",
EQBO.CUSTDFF_EDO_FLEX_STRING15 AS "MERCANCIA",
U.CUSTDFF_FLEX_STRING14 AS "Preasignado"
FROM USRTOSN4P.INV_UNIT U
LEFT OUTER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UF        ON U.GKEY = UF.UNIT_GKEY
LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED BS        ON U.LINE_OP = BS.GKEY  AND BS.ROLE = 'LINEOP'
INNER JOIN USRTOSN4P.INV_EQ_BASE_ORDER_ITEM EQBOI on U.DEPART_ORDER_ITEM_GKEY = EQBOI.GKEY
LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER EQBO on EQBO.GKEY = EQBOI.EQO_GKEY AND EQBO.SUB_TYPE = 'EDO'
LEFT OUTER JOIN USRTOSN4P.REF_EQUIPMENT RE             ON U.ID = RE.ID_FULL
LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_TYPE RET           ON RET.GKEY =RE.EQTYP_GKEY
LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_TYPE ARQ           ON ARQ.GKEY = RET.ARCHETYPE
LEFT OUTER JOIN USRTOSN4P.ARGO_CARRIER_VISIT CV        ON CV.GKEY = EQBO.VESSEL_VISIT_GKEY
LEFT OUTER JOIN USRTOSN4P.VSL_VESSEL_VISIT_DETAILS VVD ON VVD.VVD_GKEY = CV.CVCVD_GKEY
LEFT OUTER JOIN USRTOSN4P.VSL_VESSELS VS               ON VS.GKEY = VVD.VESSEL_GKEY
LEFT OUTER JOIN USRTOSN4P.SRV_EVENT EV                 ON EV.APPLIED_TO_GKEY = EQBO.GKEY
LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED BSA       ON BSA.GKEY = EQBO.AGENT_GKEY AND BSA.ROLE = 'AGENT'

WHERE
EV.EVENT_TYPE_GKEY = 179
AND EV.NOTE = U.ID
AND
EV.PLACED_TIME = (select MAX(PLACED_TIME) from USRTOSN4P.SRV_EVENT WHERE EVENT_TYPE_GKEY  = 179 AND APPLIED_TO_GKEY = EV.APPLIED_TO_GKEY AND NOTE = EV.NOTE) AND
U.COMPLEX_GKEY = 3575349411
--AND VVD.PUBLISHED_ETA < TO_DATE($P{fechaETAFinal},'YYYY/MM/DD HH24:MI')
--AND VVD.PUBLISHED_ETA > TO_DATE($P{fechaETAInicio},'YYYY/MM/DD HH24:MI')
and EQBO.CUSTDFF_EDO_FLEX_STRING11 is not null
and ROWNUM <= 100
;