SELECT ut.id, mve.*, ufv.*
FROM USRTOSN4P.inv_move_event mve
INNER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV           ON UFV.GKEY = mve.UFV_GKEY
INNER JOIN USRTOSN4P.inv_unit ut          ON ut.GKEY = UFV.UNIT_GKEY
WHERE ut.id = '58200359-1-1';
--FETCH FIRST 100 ROWS ONLY;

Select * from USRTOSN4P.crg_lots 
WHERE id = '58200359-1-1';

select * from USRTOSN4P.CRG_BL_ITEM --FETCH FIRST 100 ROWS ONLY;
WHERE GKEY ='4048200363';


--Select * from USRTOSN4P.inv_unit 
--WHERE id = 'PAMIT20008E';

--FETCH FIRST 100 ROWS ONLY;

Select * FROM USRTOSN4P.inv_move_event --FETCH FIRST 100 ROWS ONLY;
WHERE MVE_GKEY = '4048602299';


WHERE NBR LIKE '%ELL0000329/2020%'
FETCH FIRST 100 ROWS ONLY;


Select SRVTIP.ID,
SRVE.* 
FROM USRTOSN4P.srv_event SRVE
INNER JOIN USRTOSN4P.SRV_EVENT_TYPES SRVTIP ON SRVTIP.GKEY = srve.event_type_gkey
WHERE SRVE.applied_to_natural_key = 'TLLU5016433'
order by SRVE.placed_time desc;

Select * FROM USRTOSN4P.SRV_EVENT_FIELD_CHANGES
WHERE event_gkey ='4054745268';

FETCH FIRST 100 ROWS ONLY;


FETCH FIRST 100 ROWS ONLY;
--WHERE primary_event_gkey IS NOT NULL
--ORDER BY CHANGED DESC;

--Select * FROM USRTOSN4P.ARGO_CHARGEABLE_APPT_EVENTS --FETCH FIRST 100 ROWS ONLY;
--WHERE GKEY = '3156799740';

