SELECT DISTINCT
    ROWNUM AS "N°",
    RBEQ.ID AS "Linea",
    U.ID AS Contenedor,
    CASE RET.NOMINAL_LENGTH WHEN 'NOM40' THEN '40' ELSE '20' END  AS "Tam",
    CASE WHEN U.FREIGHT_KIND = 'MTY' THEN 'Vacío' ELSE U.FREIGHT_KIND END AS "ESTADO",
    TO_CHAR(UF.TIME_ECOUT,'DD-MM-YYYY')AS "FECHA MOVIMIENTO",
    EQBO.NBR AS BOOKING,
    VS.ID AS "ID NAVE",
    VVD.OB_VYG AS VIAJE,
    CASE WHEN TT.SUB_TYPE = 'DE' THEN 'Embarque' ELSE '' END AS "Tipo de Salida",
    CASE WHEN EQBO.CUSTDFF_EXPORTER_ID IS NULL THEN EQBO.CUSTDFF_EQBO_FLEX_STRING04 ELSE EQBO.CUSTDFF_EXPORTER_ID END AS "RUC/AGENTE"
FROM USRTOSN4P.ROAD_TRUCK_TRANSACTIONS TT 
    LEFT OUTER JOIN USRTOSN4P.ROAD_TRUCK_TRANSACTION_STAGES TS ON TS.TRAN_GKEY = TT.GKEY
    LEFT OUTER JOIN USRTOSN4P.INV_UNIT U                       ON U.GKEY = TT.UNIT_GKEY
    LEFT OUTER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UF            ON U.GKEY = UF.UNIT_GKEY
    LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER_ITEM EQBOI     ON U.DEPART_ORDER_ITEM_GKEY = EQBOI.GKEY
    LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER EQBO           ON EQBO.GKEY = EQBOI.EQO_GKEY
    LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED BS            ON U.LINE_OP = BS.GKEY  AND BS.ROLE = 'LINEOP'
    LEFT OUTER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV           ON U.GKEY = UFV.UNIT_GKEY
    LEFT OUTER JOIN USRTOSN4P.REF_EQUIPMENT RE                 ON U.ID = RE.ID_FULL
    LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_TYPE RET               ON RET.GKEY =RE.EQTYP_GKEY
    LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_TYPE ARQ               ON ARQ.GKEY = RET.ARCHETYPE
    LEFT OUTER JOIN USRTOSN4P.INV_GOODS GD                     ON U.GOODS = GD.GKEY
    LEFT OUTER JOIN USRTOSN4P.argo_carrier_visit CV            ON CV.GKEY = UFV.INTEND_OB_CV
    LEFT OUTER JOIN USRTOSN4P.VSL_VESSEL_VISIT_DETAILS VVD     ON VVD.VVD_GKEY = CV.CVCVD_GKEY
    LEFT OUTER JOIN USRTOSN4P.VSL_VESSELS VS                   ON VS.GKEY = VVD.VESSEL_GKEY
    LEFT OUTER JOIN USRTOSN4P.INV_EQ_STATE EQS                 ON EQS.EQ_GKEY = RE.GKEY 
    LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED RBEQ          ON RBEQ.GKEY = EQS.EQ_OWNER_GKEY
WHERE U.CATEGORY = 'EXPRT' 
        AND UF.TRANSIT_STATE = 'S70_DEPARTED' 
        AND U.FREIGHT_KIND = 'MTY'
        AND RBEQ.ID = 'HLC'
        AND U.COMPLEX_GKEY = 3575349411 
        --AND U.ID = 'TGHU6104205'
        AND TS.ID = 'OutGate'
        AND (TT.SUB_TYPE = 'DE' OR U.FLEX_STRING08 = 'Embarque')
        AND UFV.TIME_ECOUT <TO_DATE('2019/07/09 23:59', 'YYYY/MM/DD HH24:MI')
        AND UFV.TIME_ECOUT >TO_DATE('2019/06/01 23:59', 'YYYY/MM/DD HH24:MI')
ORDER BY ROWNUM ASC;