--USRTOSN4P.INV_UNIT U
--LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER_ITEM EQBOI on U.DEPART_ORDER_ITEM_GKEY = EQBOI.GKEY


SELECT RC.ID, RC.DESCRIPTION, EQBO.NBR, EQBO.CREATED
FROM USRTOSN4P.ORD_EQUIPMENT_ORDER_ITEMS OED 
INNER JOIN USRTOSN4P.INV_EQ_BASE_ORDER_ITEM EQBOI ON (OED.GKEY = EQBOI.GKEY)
INNER JOIN USRTOSN4P.INV_EQ_BASE_ORDER EQBO on EQBO.GKEY = EQBOI.EQO_GKEY
INNER JOIN USRTOSN4P.REF_COMMODITY RC ON OED.COMMODITY_GKEY = RC.GKEY;