SELECT U.ID, AF.NAME
FROM USRTOSN4P.inv_UNIT U
LEFT OUTER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV            
     ON U.GKEY = UFV.UNIT_GKEY
LEFT OUTER JOIN USRTOSN4P.argo_facility AF ON UFV.FCY_GKEY = AF.GKEY  
WHERE   UFV.TIME_ECOUT <TO_DATE('2019/07/09 23:59', 'YYYY/MM/DD HH24:MI')
    AND UFV.TIME_ECOUT >TO_DATE('2019/06/01 23:59', 'YYYY/MM/DD HH24:MI');
