
select MVE.T_CARRY_COMPLETE, U.id, U.CATEGORY,  mve.*
from USRTOSN4P.inv_move_event mve
  INNER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV           ON UFV.GKEY = mve.UFV_GKEY
    INNER JOIN USRTOSN4P.inv_unit U           ON U.GKEY = UFV.UNIT_GKEY
WHERE 
MVE.T_CARRY_COMPLETE between '07/10/2019' and '08/10/2019'
    --MVE.T_CARRY_COMPLETE >=  TO_DATE('2019-10-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
    --AND MVE.T_CARRY_COMPLETE <=  TO_DATE('2019-10-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
    --AND MVE.MOVE_KIND = 'YARD'    
   AND U.ID = 'ALHU0000334'
AND UFV.FCY_GKEY = 46182
ORDER BY U.ID;


SELECT * FROM USRTOSN4P.inv_unit U
        LEFT OUTER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV           ON U.GKEY = UFV.UNIT_GKEY
        LEFT OUTER JOIN USRTOSN4P.inv_move_event mve               ON UFV.GKEY = mve.UFV_GKEY
WHERE 
MVE.T_PUT between '07/10/2019' and '08/10/2019'
    --MVE.T_CARRY_COMPLETE >=  TO_DATE('2019-10-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
    --AND MVE.T_CARRY_COMPLETE <=  TO_DATE('2019-10-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
    --AND MVE.MOVE_KIND = 'YARD'    
   --AND U.ID = 'ALHU0000334'
AND UFV.FCY_GKEY = 46182
ORDER BY U.ID;       


SELECT MVE.T_CARRY_COMPLETE, U.id, U.CATEGORY,  
MVE.T_PUT, MVE.T_CARRY_PUT_READY,
mve.* , U.* , UFV.*
FROM USRTOSN4P.inv_unit U
LEFT OUTER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV           ON U.GKEY = UFV.UNIT_GKEY
 LEFT OUTER JOIN USRTOSN4P.inv_move_event mve               ON UFV.GKEY = mve.UFV_GKEY
WHERE U.ID = 'ALHU0000334'
ORDER BY MVE.T_CARRY_COMPLETE;
--T_PUT
--T_CARRY_PUT_READY