--SELECT * FROM USRTOSN4P.YARD_PRESTAGE_LOCATIONS;
SELECT * FROM USRTOSN4P.INV_UNIT;
SELECT transit_state FROM USRTOSN4P.INV_UNIT_FCY_VISIT
GROUP BY transit_state ;

SELECT fcy_gkey FROM USRTOSN4P.INV_UNIT_FCY_VISIT;

SELECT * FROM USRTOSN4P.INV_UNIT_FCY_VISIT;
SELECT * FROM USRTOSN4P.argo_facility_relays


SELECT COMPLEX_GKEY FROM USRTOSN4P.INV_UNIT
GROUP BY COMPLEX_GKEY ;


SELECT * FROM USRTOSN4P.argo_facility;


