--ORIGEN DESDE BL
    LEFT OUTER JOIN USRTOSN4P.REF_ROUTING_POINT RRP_BLO ON   RRP_BLO.GKEY = BL.POL_GKEY 
        LEFT OUTER JOIN USRTOSN4P.REF_UNLOC_CODE RUC_BLO ON RUC_BLO.GKEY = RRP_BLO.UNLOC_GKEY       
        LEFT OUTER JOIN USRTOSN4P.REF_COUNTRY CNTRY_BLO ON CNTRY_BLO.CNTRY_CODE = RUC_BLO.CNTRY_CODE 
    
    --DESTINO DESDE BL
    LEFT OUTER JOIN USRTOSN4P.REF_ROUTING_POINT RRP_BLD ON   RRP_BLD.GKEY = BL.POD1_GKEY     
        LEFT OUTER JOIN USRTOSN4P.REF_UNLOC_CODE RUC_BLD ON RUC_BLD.GKEY = RRP_BLD.UNLOC_GKEY       
        LEFT OUTER JOIN USRTOSN4P.REF_COUNTRY CNTRY_BLD ON CNTRY_BLD.CNTRY_CODE = RUC_BLD.CNTRY_CODE 
    
     --BOOKING origen
        LEFT OUTER JOIN USRTOSN4P.REF_ROUTING_POINT RRP_BQO ON   RRP_BQO.GKEY = EQBO.POL_GKEY 
                LEFT OUTER JOIN USRTOSN4P.REF_UNLOC_CODE  RUC_BQO ON RUC_BQO.GKEY = RRP_BQO.UNLOC_GKEY
                LEFT OUTER JOIN USRTOSN4P.REF_COUNTRY CNTRY_BQO ON CNTRY_BQO.CNTRY_CODE = RUC_BQO.CNTRY_CODE 


        --BOOKING Destino
        LEFT OUTER JOIN USRTOSN4P.REF_ROUTING_POINT RRP_BQD ON   RRP_BQD.GKEY = EQBO.POD1_GKEY 
                LEFT OUTER JOIN USRTOSN4P.REF_UNLOC_CODE  RUC_BQD ON RUC_BQD.GKEY = RRP_BQD.UNLOC_GKEY
                LEFT OUTER JOIN USRTOSN4P.REF_COUNTRY CNTRY_BQD ON CNTRY_BQD.CNTRY_CODE = RUC_BQD.CNTRY_CODE 