
Select 
'DPWCALLAO' as bu_name,
CASE WHEN U.category = 'EXPRT' THEN 'Export'  WHEN U.category = 'IMPRT' THEN 'Import' END  as impexp_typr,
U.ID    as container_num,
RFS.name  as shipping_line_operator,
VS.name as Vessel,
VVD.IB_VYG as voyage_num,
TO_CHAR(CV.ATA, 'YYYYMMDD') as arrival_date,
TO_CHAR(CV.ATD, 'YYYYMMDD') as departure_date,
RUC_ORI.PLACE_NAME ||' , '|| CNTRY_ORI.CNTRY_NAME AS Origin_Country,
RUC_BQO.PLACE_NAME ||' , '|| CNTRY_BQO.CNTRY_NAME AS port_of_landing,
RUC_DES.PLACE_NAME ||' , '|| CNTRY_DES.CNTRY_NAME AS destination_country,
RUC_BQD.PLACE_NAME ||' , '|| CNTRY_BQD.CNTRY_NAME AS port_of_unlading,
CASE RET.NOMINAL_LENGTH WHEN 'NOM40' THEN 2 ELSE 1 END  AS TEU,
'' as Goods_Value_USD,
'' as notifier_name,
RFS_CN.ID as Consignee_name,
RFS_SH.ID as shipper_name,
'' AS item_description,
U.CUSTDFF_BL_MASTER as bl_no
From USRTOSN4P.inv_unit U
    LEFT OUTER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV           ON U.GKEY = UFV.UNIT_GKEY
    LEFT OUTER JOIN USRTOSN4P.argo_carrier_visit CV            ON (CV.GKEY = UFV.INTEND_OB_CV OR CV.GKEY = U.DECLRD_IB_CV)
    LEFT OUTER JOIN USRTOSN4P.vsl_vessel_visit_details VVD     ON CV.CVCVD_GKEY = VVD.VVD_GKEY
    LEFT OUTER JOIN USRTOSN4P.VSL_VESSELS VS                   ON VS.GKEY = VVD.VESSEL_GKEY
    LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED RFS          ON RFS.GKEY = U.LINE_OP
    
    LEFT OUTER JOIN USRTOSN4P.CRG_BILLS_OF_LADING BL           ON BL.NBR = U.CUSTDFF_BL_MASTER AND BL.COMPLEX_GKEY = U.COMPLEX_GKEY
    LEFT OUTER JOIN USRTOSN4P.REF_ROUTING_POINT RRP_ORI ON   RRP_ORI.GKEY = U.OPL_GKEY 
    LEFT OUTER JOIN USRTOSN4P.REF_UNLOC_CODE  RUC_ORI ON RUC_ORI.GKEY = RRP_ORI.UNLOC_GKEY
                LEFT OUTER JOIN USRTOSN4P.REF_COUNTRY CNTRY_ORI ON CNTRY_ORI.CNTRY_CODE = RUC_ORI.CNTRY_CODE 
    LEFT OUTER JOIN USRTOSN4P.REF_ROUTING_POINT RRP_DES ON   RRP_DES.GKEY = U.POD2_GKEY 
    LEFT OUTER JOIN USRTOSN4P.REF_UNLOC_CODE  RUC_DES ON RUC_DES.GKEY = RRP_DES.UNLOC_GKEY
                LEFT OUTER JOIN USRTOSN4P.REF_COUNTRY CNTRY_DES ON CNTRY_DES.CNTRY_CODE = RUC_DES.CNTRY_CODE 
    LEFT OUTER JOIN USRTOSN4P.REF_ROUTING_POINT RRP_BQO ON   RRP_BQO.GKEY = U.POL_GKEY 
                LEFT OUTER JOIN USRTOSN4P.REF_UNLOC_CODE  RUC_BQO ON RUC_BQO.GKEY = RRP_BQO.UNLOC_GKEY
                LEFT OUTER JOIN USRTOSN4P.REF_COUNTRY CNTRY_BQO ON CNTRY_BQO.CNTRY_CODE = RUC_BQO.CNTRY_CODE 
    LEFT OUTER JOIN USRTOSN4P.REF_ROUTING_POINT RRP_BQD ON   RRP_BQD.GKEY = U.POD1_GKEY 
                LEFT OUTER JOIN USRTOSN4P.REF_UNLOC_CODE  RUC_BQD ON RUC_BQD.GKEY = RRP_BQD.UNLOC_GKEY
                LEFT OUTER JOIN USRTOSN4P.REF_COUNTRY CNTRY_BQD ON CNTRY_BQD.CNTRY_CODE = RUC_BQD.CNTRY_CODE
    LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER_ITEM EQBOI on U.DEPART_ORDER_ITEM_GKEY = EQBOI.GKEY
    LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER EQBO on EQBO.GKEY = EQBOI.EQO_GKEY  
        LEFT OUTER JOIN USRTOSN4P.REF_EQUIPMENT RE ON U.ID = RE.ID_FULL
        LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_TYPE RET  ON RET.GKEY =RE.EQTYP_GKEY
    LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED RFS_CN       ON RFS_CN.GKEY = BL.CONSIGNEE_GKEY
    LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED RFS_SH       ON RFS_SH.GKEY = BL.SHIPPER_GKEY
WHERE U.category IN ('IMPRT')
--AND EXTRACT(YEAR FROM CV.ATA) IN (2018,2019)
--and CV.ATA between '01/06/2019' and '26/09/2019'
and VVD.PUBLISHED_ETA between '01/06/2019' and '26/09/2019'
AND UFV.FCY_GKEY = 3575349497; --ARGENTINA
--AND U.ID = 'TEMU8724034';
--AND ROWNUM <= 1000;

