select COUNT(*)

from USRTOSN4P.inv_move_event mve
  INNER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV           ON UFV.GKEY = mve.UFV_GKEY
    INNER JOIN USRTOSN4P.inv_unit U           ON U.GKEY = UFV.UNIT_GKEY
    INNER JOIN USRTOSN4P.SRV_EVENT SRV        ON MVE.MVE_GKEY = SRV.GKEY
    INNER JOIN USRTOSN4P.SRV_EVENT_TYPES evnttype ON evnttype.GKEY = SRV.EVENT_TYPE_GKEY
    LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED RFS          ON RFS.GKEY = U.LINE_OP 
 
    LEFT OUTER JOIN USRTOSN4P.XPS_CHE CHEF       ON CHEF.GKEY = MVE.CHE_FETCH
    LEFT OUTER JOIN USRTOSN4P.XPS_CHE CHEC       ON CHEC.GKEY = MVE.CHE_CARRY
    LEFT OUTER JOIN USRTOSN4P.XPS_CHE CHEP       ON CHEP.GKEY = MVE.CHE_PUT
    
    --LEFT OUTER JOIN USRTOSN4P.SPATIAL_BINS SPBF ON SPBF.GKEY = MVE.TO_POS_BIN
    --LEFT OUTER JOIN USRTOSN4P.SPATIAL_BINS SPBT ON SPBT.GKEY = MVE.FM_POS_BIN
    
    LEFT OUTER JOIN USRTOSN4P.INV_GOODS GD                 ON U.GOODS = GD.GKEY
    
    
    
WHERE evnttype.ID IN ('UNIT_YARD_MOVE','UNIT_YARD_SHIFT')
    AND MVE.T_PUT >=  TO_DATE('2018-12-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
    AND MVE.T_PUT <=  TO_DATE('2019-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')   --MVE.T_PUT between '07/10/2019' and '08/10/2019'
 --AND U.ID = 'TGHU6314367'    
AND UFV.FCY_GKEY = 46182
--AND ( CHEC.FULL_NAME LIKE 'RS%' OR CHEC.FULL_NAME LIKE 'EH%' OR CHEC.FULL_NAME IS NULL) --AS "Carry CHE Name",
--AND ( CHEF.FULL_NAME LIKE 'RS%' OR CHEF.FULL_NAME  LIKE 'EH%' OR CHEF.FULL_NAME  IS NULL) --AS "Fetch CHE Name",
--AND ( CHEP.FULL_NAME LIKE 'RS%' OR CHEP.FULL_NAME   LIKE 'EH%' OR CHEP.FULL_NAME   IS NULL)--CHEP.FULL_NAMEAS "Put CHE Name",
AND ( SUBSTR(CHEC.FULL_NAME ,1,2) IN ('RS','ES') OR CHEC.FULL_NAME IS NULL )
ORDER BY U.ID;
  
 