select 
TO_CHAR (MVE.T_PUT , 'YYYY-MM-DD HH24:MI') AS "Time Completed", 
TO_CHAR (mve.t_carry_fetch_ready , 'YYYY-MM-DD HH24:MI') AS "Time Carry Che Ready",
evnttype.ID AS "Event ID",
'Yard ' || initcap(trim(SUBSTR(evnttype.ID ,11,length(evnttype.ID)))) AS "Move Kind",  --evnttype.ID AS "Move Kind"
CASE U.CATEGORY  WHEN 'EXPRT' THEN 'Export' WHEN 'IMPRT' THEN 'Import' WHEN 'TRSHP' THEN 'TransShip' WHEN 'THRGH' THEN 'FALTACONSULTAR' WHEN 'STRGE' THEN 'FALTACONSULTAR' END AS "Unit Category",  --U.CATEGORY AS "Unit Category",
U.id    AS "Unit Nbr",
RFS.ID AS "Line Op",
MVE.CHE_PUT_LOGIN_NAME AS "Put CHE Login Name",
MVE.CHE_FETCH_LOGIN_NAME AS "Fetch CHE Login Name",
MVE.REHANDLE_COUNT AS "Rehandle Count",
--u.flex_string10 AS "Unit Deposito Temporal",
TRUNC(NVL(TRUNC(ufv.time_out),CURRENT_DATE) - TRUNC(ufv.time_in)) as "Unit Dwell",

--CASE  WHEN (SUBSTR(CHEC.FULL_NAME ,1,2) = 'RS' AND SUBSTR(CHEC.FULL_NAME ,1,2)= 'ES') THEN CHEC.FULL_NAME ELSE '' END AS "Carry CHE Name",
--CASE SUBSTR(CHEF.FULL_NAME  ,1,2) WHEN 'RS' THEN CHEF.FULL_NAME  ELSE '' END AS "Fetch CHE Name",
--CASE SUBSTR(CHEP.FULL_NAME ,1,2) WHEN 'RS' THEN CHEP.FULL_NAME ELSE '' END AS "Put CHE Name",

CHEC.FULL_NAME AS "Carry CHE Name_T",
CHEF.FULL_NAME AS "Fetch CHE Name_T",
CHEP.FULL_NAME AS "Put CHE Name_T",


MVE.FM_POS_NAME AS "From Position",
MVE.TO_POS_NAME AS "To Position",
CASE GD.HAZARDOUS   WHEN 0 THEN 'false' ELSE 'true'  END AS "Unit Hazardous?",    --GD.HAZARDOUS AS "Unit Hazardous?",
CASE U.REQUIRES_POWER   WHEN 0 THEN 'false' ELSE 'true'  END AS "Unit Reqs Power",    --   U.REQUIRES_POWER AS "Unit Reqs Power", 
CASE U.IS_OOG   WHEN 0 THEN 'false' ELSE 'true'  END AS "Unit Is OOG"      --U.IS_OOG AS "Unit Is OOG" 

--TRUNC(ufv.time_in) - 0 as "DwellINVERTIDO",
--ufv.time_out,
--ufv.time_IN

--CheFetchLoginName
--mve.*,
--u.*, 
--ufv.* 
from USRTOSN4P.inv_move_event mve
  INNER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV           ON UFV.GKEY = mve.UFV_GKEY
    INNER JOIN USRTOSN4P.inv_unit U           ON U.GKEY = UFV.UNIT_GKEY
    INNER JOIN USRTOSN4P.SRV_EVENT SRV        ON MVE.MVE_GKEY = SRV.GKEY
    INNER JOIN USRTOSN4P.SRV_EVENT_TYPES evnttype ON evnttype.GKEY = SRV.EVENT_TYPE_GKEY
    LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED RFS          ON RFS.GKEY = U.LINE_OP 
 
    LEFT OUTER JOIN USRTOSN4P.XPS_CHE CHEF       ON CHEF.GKEY = MVE.CHE_FETCH
    LEFT OUTER JOIN USRTOSN4P.XPS_CHE CHEC       ON CHEC.GKEY = MVE.CHE_CARRY
    LEFT OUTER JOIN USRTOSN4P.XPS_CHE CHEP       ON CHEP.GKEY = MVE.CHE_PUT
    
    --LEFT OUTER JOIN USRTOSN4P.SPATIAL_BINS SPBF ON SPBF.GKEY = MVE.TO_POS_BIN
    --LEFT OUTER JOIN USRTOSN4P.SPATIAL_BINS SPBT ON SPBT.GKEY = MVE.FM_POS_BIN
    
    LEFT OUTER JOIN USRTOSN4P.INV_GOODS GD                 ON U.GOODS = GD.GKEY
    
    
    
WHERE --evnttype.ID IN ('UNIT_YARD_MOVE','UNIT_YARD_SHIFT')

     MVE.T_carry_complete >  TO_DATE('2019-12-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
    AND MVE.T_carry_complete < TO_DATE('2019-12-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS')   --MVE.T_PUT between '07/10/2019' and '08/10/2019'

    --MVE.T_PUT >=  TO_DATE('2018-12-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
    --AND MVE.T_PUT <  TO_DATE('2019-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')   --MVE.T_PUT between '07/10/2019' and '08/10/2019'

 --AND U.ID = 'TGHU6314367'    
AND UFV.FCY_GKEY = 46182
--AND SUBSTR(CHEC.FULL_NAME ,1,2) IN ('RS','ES')
--AND ( CHEC.FULL_NAME LIKE 'RS%' OR CHEC.FULL_NAME LIKE 'EH%' OR CHEC.FULL_NAME IS NULL) --AS "Carry CHE Name",
--AND ( CHEF.FULL_NAME LIKE 'RS%' OR CHEF.FULL_NAME  LIKE 'EH%' OR CHEF.FULL_NAME  IS NULL) --AS "Fetch CHE Name",
--AND ( CHEP.FULL_NAME LIKE 'RS%' OR CHEP.FULL_NAME   LIKE 'EH%' OR CHEP.FULL_NAME   IS NULL)--CHEP.FULL_NAMEAS "Put CHE Name",

ORDER BY MVE.T_PUT ;
  --4,871
 