
--DEFINE V_ID = 'CMAU4135668'
DEFINE V_DATEINI = TO_DATE('07-10-2019')
DEFINE V_DATEFIN = TO_DATE('08-10-2019')


SELECT * --, eq_subclass, id_prefix , class 
FROM USRTOSN4P.REF_EQUIPMENT
WHERE CREATED > &V_DATEINI 
  AND CREATED > &V_DATEFIN ;
--WHERE id = '&V_ID';



