SELECT 
CASE WHEN rda.CTR_ID IS NULL THEN ' ' ELSE rda.CTR_ID END AS "Ctr Id",
CASE WHEN UFV.LAST_POS_NAME IS NULL THEN ' ' ELSE UFV.LAST_POS_NAME END AS "Curr Position",
TO_CHAR(rda.REQUESTED_TIME,'YYYY-MM-DD') AS "Date",
rda.UFV_FLEX_STRING07 AS "Flex Tipo de Cita NSGC",
rda.ID AS "Nbr",
TO_CHAR(aps.START_DATE,'YYYY-MM-DD HH24:MI') AS "Slot Start Time",
rda.STATE AS "State",
CASE WHEN rda.TRANS_TYPE = 'PUI' THEN 'Pick Up Import' ELSE 
CASE WHEN rda.TRANS_TYPE = 'PUE' THEN 'Pick Up Export' ELSE
CASE WHEN rda.TRANS_TYPE = 'DOI' THEN 'Drop Off Import' ELSE
CASE WHEN rda.TRANS_TYPE = 'DOM' THEN 'Drop Off Empty' ELSE 
CASE WHEN rda.TRANS_TYPE = 'DOE' THEN 'Drop Off Export' ELSE
CASE WHEN rda.TRANS_TYPE = 'PUM' THEN 'Pick Up Empty' ELSE 
rda.TRANS_TYPE
END 
END 
END
END
END
END
AS "Trans Type",
CASE WHEN rda.TRUCK_LICENSE_NBR IS NULL THEN ' ' ELSE rda.TRUCK_LICENSE_NBR END AS "Truck License",
BSA.ID AS "Trucking Company"

FROM USRTOSN4P.ROAD_GATE_APPOINTMENT rda 
INNER JOIN USRTOSN4P.INV_UNIT ut                ON ut.GKEY = rda.UNIT_GKEY
INNER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV     ON ut.GKEY = ufv.UNIT_GKEY
INNER JOIN USRTOSN4P.ROAD_APPT_TIME_SLOT APS ON APS.GKEY = rda.TIME_SLOT_GKEY
LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED BSA ON BSA.GKEY =  RDA.TRKCO_GKEY
WHERE
--rda.REQUESTED_TIME < = TRUNC(SYSDATE) AND 
--rda.id  = 6748146 and
rda.REQUESTED_TIME >= TRUNC(SYSDATE)-111 AND
UFV.FCY_GKEY = 3334231702;
