Select Distinct
CASE WHEN mve.MOVE_KIND  = 'RECV' THEN ufv.ARRIVE_POS_LOCID ELSE
CASE WHEN  mve.MOVE_KIND  ='DLVR' THEN ufv.LAST_POS_LOCID ELSE ufv.LAST_POS_LOCID END END AS "Carrier Visit",


CASE WHEN chec.FULL_NAME IS NULL THEN ' ' ELSE chec.FULL_NAME END AS "Carry CHE Name",
CASE WHEN checr.full_name IS NULL THEN ' ' ELSE checr.full_name END AS "Crane CHE Name",
CASE WHEN chef.FULL_NAME IS NULL THEN ' ' ELSE chef.FULL_NAME END AS "Fetch CHE Name",
mve.FM_POS_NAME AS "From Position",
CASE mve.MOVE_KIND
  WHEN 'RECV' THEN 'Receival'
  WHEN 'DLVR' THEN 'Delivery'
  else mve.MOVE_KIND
END AS "Move Kind",
CASE WHEN mve.CHE_PUT_LOGIN_NAME IS NULL THEN ' ' ELSE mve.CHE_PUT_LOGIN_NAME END AS "Put CHE Login Name",
CASE WHEN chep.FULL_NAME IS NULL THEN ' ' ELSE chep.FULL_NAME END AS "Put CHE Name",
TO_CHAR(mve.T_PUT,'YYYY-MM-DD HH24:MI') AS "Time Completed",
mve.TO_POS_NAME AS "To Position",
CASE ut.category
  WHEN 'IMPRT' THEN 'Import'
  WHEN 'EXPRT' THEN 'Export'
  WHEN 'THRGH' THEN 'Through'
  WHEN 'TRSHP' THEN 'Transship'
  WHEN 'STRGE' THEN 'Storage'
  else ut.category
END AS "Unit Category",
CASE WHEN ut.FLEX_STRING10 IS NULL THEN ' ' ELSE ut.FLEX_STRING10 END AS "Unit Deposito Temporal",
ufv.ARRIVE_POS_LOCID AS "Unit I/B Actual Visit",
ut.IS_OOG AS "Unit Is OOG",
ufv.LAST_POS_LOCID AS "Unit O/B Actual Visit",
TO_CHAR(ufv.TIME_IN,'YYYY-MM-DD HH24:MI') AS "Unit Time In",
CASE WHEN TO_CHAR(ufv.TIME_OUT,'YYYY-MM-DD HH24:MI') IS NULL THEN ' ' ELSE TO_CHAR(ufv.TIME_OUT,'YYYY-MM-DD HH24:MI') END AS "Unit Time Out",
CASE ret.nominal_height
  WHEN 'NOM96' THEN '9''6'''''
  WHEN 'NOM86' THEN '8''6'''''
  else ret.nominal_height
END AS "Unit Type Height",
ret.id AS "Unit Type ISO",
CASE ret.nominal_length
  WHEN 'NOM40' THEN '40'''
  WHEN 'NOM20' THEN '20'''
  else RET.nominal_length
END AS "Unit Type Length",
ut.GOODS_AND_CTR_WT_KG AS "Unit Weight (kg)",
--TO_CHAR(year(ufv.TIME_IN),'YYYY-MM-DD HH24:MI') AS "Año"
--year(ufv.TIME_IN)
TO_CHAR(ufv.TIME_IN,'YYYY') AS "Año",
TO_CHAR(ufv.TIME_IN,'MM') AS "Mes",
TO_CHAR(ufv.TIME_IN,'HH24:MI') AS "Hora",
AF.NAME AS "Sede",
CASE WHEN RE.RFR_TYPE ='NON_RFR' THEN 'DRY' ELSE 'REEFER' END AS "TIPOCONTENEDOR DRY/REEFER",
--EQBO.HAS_REEFERS,
CASE mve.MOVE_KIND
  WHEN 'RECV' THEN (CASE WHEN chep.FULL_NAME IS NULL THEN ' ' ELSE chep.FULL_NAME END)
  WHEN 'DLVR' THEN (CASE WHEN chef.FULL_NAME IS NULL THEN ' ' ELSE chef.FULL_NAME END)
  else mve.MOVE_KIND
END AS "Utilización de equipo",
--LLENO O VACIO  DEFINIR...............
UT.FREIGHT_KIND, 
--EQBO.CUSTDFF_EQBO_FLEX_STRING05,
--********************************************************
ut.id AS "Unit Nbr",
EQBO.NBR AS "BOOKING",
NVL(EQBO.CUSTDFF_EQBO_FLEX_STRING11, EQBO.CUSTDFF_EQBO_FLEX_STRING06) AS "Integral",  
ufv.time_move AS "Last Move",
ufv.transit_state as "T-STATE",                 --LUCERO
CASE ut.category
  WHEN 'IMPRT' THEN 'Import'
  WHEN 'EXPRT' THEN 'Export'
  WHEN 'THRGH' THEN 'Through'
  WHEN 'TRSHP' THEN 'Transship'
  WHEN 'STRGE' THEN 'Storage'
  else ut.category
END AS "Categoria",
BS.NAME AS "LINE OP",
BL.CUSTDFF_BL_FLEX_STRING03 AS "RUC Facturar A:"


From USRTOSN4P.INV_MOVE_EVENT mve

    INNER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV           ON UFV.GKEY = mve.UFV_GKEY
    INNER JOIN USRTOSN4P.inv_unit ut          ON ut.GKEY = UFV.UNIT_GKEY
    INNER JOIN USRTOSN4P.REF_EQUIPMENT RE ON ut.ID = RE.ID_FULL
    INNER JOIN USRTOSN4P.REF_EQUIP_TYPE RET  ON RET.GKEY =RE.EQTYP_GKEY
    
    
    
    LEFT OUTER JOIN USRTOSN4P.XPS_CHE CHEC       ON CHEC.GKEY = MVE.CHE_CARRY
    LEFT OUTER JOIN USRTOSN4P.XPS_CHE CHEF       ON CHEF.GKEY = MVE.CHE_FETCH
    LEFT OUTER JOIN USRTOSN4P.XPS_CHE CHECR       ON CHECR.GKEY = MVE.CHE_QC
    LEFT       JOIN USRTOSN4P.XPS_CHE CHEP       ON CHEP.GKEY = MVE.CHE_PUT
    
    LEFT OUTER JOIN USRTOSN4P.ARGO_FACILITY AF ON AF.GKEY = UFV.FCY_GKEY
    
    
    LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER_ITEM EQBOI on ut.DEPART_ORDER_ITEM_GKEY = EQBOI.GKEY
    LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER EQBO on EQBO.GKEY = EQBOI.EQO_GKEY   --BOOKING

    LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED BS        ON UT.LINE_OP = BS.GKEY  AND BS.ROLE = 'LINEOP'
    
    
    LEFT OUTER JOIN USRTOSN4P.ROAD_TRUCK_TRANSACTIONS RTT ON UT.GKEY = RTT.UNIT_GKEY
    INNER JOIN USRTOSN4P.ROAD_TRUCK_VISIT_DETAILS RTVD     ON RTT.TRUCK_VISIT_GKEY = RTVD.TVDTLS_GKEY
        LEFT JOIN USRTOSN4P.CRG_BILLS_OF_LADING BL ON BL.GKEY = RTT.BL_GKEY


WHERE
mve.MOVE_KIND in ('RECV','DLVR')  AND
--ut.ID = 'WHLU0565353' AND
--mve.T_PUT >= TRUNC(SYSDATE)-30  AND
mve.T_PUT >=  TO_DATE('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AND
UFV.FCY_GKEY IN (3575349497,3575349521,3334231702);
--and BL.CUSTDFF_BL_FLEX_STRING03 is not null;
--= 3575349497; 

--select * from USRTOSN4P.ARGO_FACILITY;