select * from USRTOSN4P.CARGOLOT_EVENTS_HISTORY;

select * from USRTOSN4P.SRV_EVENT_TYPES;


SELECT * 
FROM USRTOSN4P.inv_move_event mve
INNER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV           ON UFV.GKEY = mve.UFV_GKEY
WHERE mve.T_PUT >= TRUNC(SYSDATE)-30  AND
--mve.T_PUT <  TO_DATE('2019-11-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AND
UFV.FCY_GKEY = 3575349497;


SELECT * FROM USRTOSN4P.INV_MOVE_EVENT  FETCH FIRST 100 ROWS ONLY;
--WHERE PRIMARY_EVENT_GKEY IS NOT NULL

--SELECT * FROM USRTOSN4P.eventsViewUiTableManager

/*
SELECT * FROM USRTOSN4P.inv_unitFETCH FIRST 100 ROWS ONLY
SELECT * FROM USRTOSN4P.crg_lots FETCH FIRST 100 ROWS ONLY


----
--

SELECT * FROM USRTOSN4P.inv_move_event FETCH FIRST 100 ROWS ONLY
*/

SELECT * FROM USRTOSN4P.crg_lots --FETCH FIRST 100 ROWS ONLY
where blitem_ib_gkey = '3946910331';


SELECT * FROM USRTOSN4P.CRG_BL_ITEM  --FETCH FIRST 100 ROWS ONLY;
where gkey = '3946910331';




--FETCH FIRST 100 ROWS ONLY;