SELECT 

RTVD.TRUCK_LICENSE_NBR AS "Truck Visit Truck License",
			 CASE WHEN RTT.SUB_TYPE = 'RE' THEN 'Receive Export' ELSE 
             CASE WHEN RTT.SUB_TYPE = 'RB' THEN 'Receive Break-Bulk' ELSE 
             CASE WHEN RTT.SUB_TYPE = 'DI' THEN 'Deliver Import' ELSE 
             CASE WHEN RTT.SUB_TYPE = 'RM' THEN 'Receive Empty' ELSE 
             CASE WHEN RTT.SUB_TYPE = 'DM' THEN 'Deliver Empty' ELSE 
             CASE WHEN RTT.SUB_TYPE = 'RI' THEN 'Receive Import' ELSE 
             CASE WHEN RTT.SUB_TYPE = 'DE' THEN 'Deliver Export' ELSE 
             RTT.SUB_TYPE 
             END 
             END 
             END 
             END 
             END 
             END 
             END AS "Transaction Type", 
CASE WHEN RTT.CTR_ID IS NULL THEN ' ' ELSE RTT.CTR_ID END AS "Ctr Number",
RTT.NBR AS "Number",
CASE WHEN RTT.IS_OOG =0 THEN 'false' ELSE 'true' END AS "OOG",
RTT.STATUS AS "Status",
RTT.CTR_TICKET_POS_ID AS "Ticket Position",
CASE WHEN RTVD.BAT_NBR IS NULL THEN ' ' ELSE RTVD.BAT_NBR END AS "Truck Visit BAT Number",
TO_CHAR(RTVD.ENTERED_YARD,'YYYY-MM-DD HH24:MI') AS "Truck Visit Entered Yard",
CASE WHEN TO_CHAR(RTVD.EXITED_YARD,'YYYY-MM-DD HH24:MI') IS NULL THEN ' ' ELSE TO_CHAR(RTVD.EXITED_YARD,'YYYY-MM-DD HH24:MI') END AS "Truck Visit Exited Yard",
RTT.TRKCO_ID AS "Trucking Co Id",
CASE WHEN RTT.TRAN_FLEX_STRING05 IS NULL THEN ' ' ELSE RTT.TRAN_FLEX_STRING05 END AS "Yard Turnaround",
BST.NAME AS "Trucking Company Name",
CASE WHEN UT.FLEX_STRING10 IS NULL THEN ' ' ELSE UT.FLEX_STRING10 END AS "Unit Deposito Temporal",
CASE WHEN CV.ID IS NULL THEN ' ' ELSE CV.ID END AS "Vessel Visit Tran"



FROM USRTOSN4P.ROAD_TRUCK_TRANSACTIONS RTT 
INNER JOIN USRTOSN4P.INV_UNIT UT           ON UT.GKEY = RTT.UNIT_GKEY
INNER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV     ON ut.GKEY = ufv.UNIT_GKEY
INNER JOIN USRTOSN4P.ROAD_TRUCK_VISIT_DETAILS RTVD     ON RTT.TRUCK_VISIT_GKEY = RTVD.TVDTLS_GKEY
LEFT JOIN USRTOSN4P.ARGO_CARRIER_VISIT CV ON RTT.CV_GKEY = CV.GKEY
LEFT JOIN USRTOSN4P.REF_BIZUNIT_SCOPED BST ON BST.GKEY =  RTT.TRKCO_GKEY
WHERE 
--TRUNC(TRUNC(SYSDATE) - TRUNC(RTT.CREATED))<=24
RTVD.ENTERED_YARD >= TRUNC(SYSDATE)-111
AND UFV.FCY_GKEY = 3334231702 
AND RTT.STATUS IN ('OK','COMPLETE');