SELECT 

RTVD.GOS_TV_KEY AS "Gate Visit Nbr",
TO_CHAR(RTVD.ENTERED_YARD,'YYYY-MM-DD HH24:MI') AS "Entered Yard",
TO_CHAR(RTVD.EXITED_YARD,'YYYY-MM-DD HH24:MI') AS"Exited Yard",

ROUND((TO_DATE(TO_CHAR(RTVD.EXITED_YARD,'DD/MM/YYYY HH24:MI'),'DD/MM/YYYY HH24:MI')-
TO_DATE(TO_CHAR(RTVD.ENTERED_YARD,'DD/MM/YYYY HH24:MI'),'DD/MM/YYYY HH24:MI'))*60*24)  AS "Minutes In Yard",

ARLEN.ID AS "Entry Lane",
AREX.ID AS "Exit Lane",
RTVD.CREATOR AS "Creator",
RTVD.SCALE_WEIGHT AS "Peso Destare (kg)",
RTVD.TRUCK_ID AS "Truck Id",
RTVD.TRUCK_LICENSE_NBR AS "Truck License",
RCP.ID AS "Chs Profile",
RTVD.DRIVER_NAME AS "Driver Name",
RTVD.DRIVER_LICENSE_NBR AS "Driver License",
RTVD.DRIVER_CARD_ID AS "Driver Card",
RTVD.TRUCKING_CO_ID AS "Trucking Company",
COUNT(*) AS "Transaction Count",
RTVD.STATUS AS "Truck Visit Status"

FROM USRTOSN4P.ROAD_TRUCK_VISIT_DETAILS RTVD

INNER JOIN USRTOSN4P.ROAD_TRUCK_TRANSACTIONS RTT     ON RTT.TRUCK_VISIT_GKEY = RTVD.TVDTLS_GKEY
INNER JOIN USRTOSN4P.INV_UNIT UT                     ON UT.GKEY = RTT.UNIT_GKEY
INNER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV          ON ut.GKEY = ufv.UNIT_GKEY
INNER JOIN USRTOSN4P.ROAD_CHASSIS_PROFILES  RCP      ON RCP.GKEY = RTVD.CHPRO_GKEY

LEFT JOIN USRTOSN4P.ARGO_LANES ARLEN                 ON ARLEN.GKEY = RTVD.ENTRY_GATELN_GKEY
LEFT JOIN USRTOSN4P.ARGO_LANES AREX                  ON AREX.GKEY = RTVD.EXIT_GATELN_GKEY

WHERE 
--RTVD.CREATED>='13/01/20' AND
--RTVD.GOS_TV_KEY='1427111' AND 
RTVD.ENTERED_YARD >= TRUNC(SYSDATE)-111 AND
UFV.FCY_GKEY = 3334231702 AND
RTVD.STATUS='COMPLETE'

GROUP BY RTVD.GOS_TV_KEY,RTVD.ENTERED_YARD,RTVD.EXITED_YARD,ARLEN.ID,AREX.ID,RTVD.CREATOR,RTVD.SCALE_WEIGHT,RTVD.TRUCK_ID,RTVD.TRUCK_LICENSE_NBR,
RCP.ID,RTVD.DRIVER_NAME,RTVD.DRIVER_LICENSE_NBR,RTVD.DRIVER_CARD_ID,RTVD.TRUCKING_CO_ID,RTVD.STATUS;