SELECT * FROM
(
SELECT 
    RTVD.GOS_TV_KEY AS "Gate Visit Nbr",
    TO_CHAR(RTVD.ENTERED_YARD,'YYYY-MM-DD HH24:MI') AS "Entered Yard",
    TO_CHAR(RTVD.EXITED_YARD,'YYYY-MM-DD HH24:MI') AS"Exited Yard",
    
    ROUND((TO_DATE(TO_CHAR(RTVD.EXITED_YARD,'DD/MM/YYYY HH24:MI'),'DD/MM/YYYY HH24:MI')-
    TO_DATE(TO_CHAR(RTVD.ENTERED_YARD,'DD/MM/YYYY HH24:MI'),'DD/MM/YYYY HH24:MI'))*60*24)  AS "Minutes In Yard",
    
    ARLEN.ID AS "Entry Lane",
    AREX.ID AS "Exit Lane",
    RTVD.CREATOR AS "Creator",
    RTVD.SCALE_WEIGHT AS "Peso Destare (kg)",
    RTVD.TRUCK_ID AS "Truck Id",
    RTVD.TRUCK_LICENSE_NBR AS "Truck License",
    RCP.ID AS "Chs Profile",
    RTVD.DRIVER_NAME AS "Driver Name",
    RTVD.DRIVER_LICENSE_NBR AS "Driver License",
    RTVD.DRIVER_CARD_ID AS "Driver Card",
    RTVD.TRUCKING_CO_ID AS "Trucking Company",
    COUNT(*) AS "Transaction Count",
    RTVD.STATUS AS "Truck Visit Status",
    
    
    TO_CHAR(RTVD.ENTERED_YARD,'YYYY') AS "Año",
    TO_CHAR(RTVD.ENTERED_YARD,'MM') AS "Mes",
    
    UT.ID AS "CONTENEDOR",
    eqbo.nbr as "BOOKING",
    
    CASE RTT.SUB_TYPE
    WHEN 'RI' THEN 'DRAY-IN'
    WHEN 'RE' THEN 'RECEIVE EXPORT'
    WHEN 'RM' THEN 'RECEIVE EMPTY'
    WHEN 'RB' THEN 'RECEIVE BREAK-BULK'
    WHEN 'DI' THEN 'DELIVER IMPORT'
    WHEN 'DM' THEN 'DELIVER EMPTY'
    WHEN 'DE' THEN 'DRAY OFF'
    END AS "TRANS TYPE",
    
    
    CASE ut.category
  WHEN 'IMPRT' THEN 'Import'
  WHEN 'EXPRT' THEN 'Export'
  WHEN 'THRGH' THEN 'Through'
  WHEN 'TRSHP' THEN 'Transship'
  WHEN 'STRGE' THEN 'Storage'
  else ut.category  END AS "Unit Category",

--EQBO.HAS_REEFERS,
CASE WHEN RE.RFR_TYPE ='NON_RFR' THEN 'DRY' ELSE 'REEFER' END AS "TIPOCONTENEDOR DRY/REEFER",

UT.FREIGHT_KIND,
ret.id AS "Unit Type ISO"
    
    
    FROM USRTOSN4P.ROAD_TRUCK_VISIT_DETAILS RTVD
    
    INNER JOIN USRTOSN4P.ROAD_TRUCK_TRANSACTIONS RTT     ON RTT.TRUCK_VISIT_GKEY = RTVD.TVDTLS_GKEY
    INNER JOIN USRTOSN4P.INV_UNIT UT                     ON UT.GKEY = RTT.UNIT_GKEY
    INNER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV          ON ut.GKEY = ufv.UNIT_GKEY
    INNER JOIN USRTOSN4P.ROAD_CHASSIS_PROFILES  RCP      ON RCP.GKEY = RTVD.CHPRO_GKEY
    
    LEFT JOIN USRTOSN4P.ARGO_LANES ARLEN                 ON ARLEN.GKEY = RTVD.ENTRY_GATELN_GKEY
    LEFT JOIN USRTOSN4P.ARGO_LANES AREX                  ON AREX.GKEY = RTVD.EXIT_GATELN_GKEY
    
        
    INNER JOIN USRTOSN4P.REF_EQUIPMENT RE ON ut.ID = RE.ID_FULL
    INNER JOIN USRTOSN4P.REF_EQUIP_TYPE RET  ON RET.GKEY =RE.EQTYP_GKEY
    
    
    LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER_ITEM EQBOI on ut.DEPART_ORDER_ITEM_GKEY = EQBOI.GKEY
    LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER EQBO on EQBO.GKEY = EQBOI.EQO_GKEY   

    
    WHERE 
--    RTVD.ENTERED_YARD >= TRUNC(SYSDATE)-20 AND
--    UFV.FCY_GKEY = 3575349497 AND
    RTVD.ENTERED_YARD >= TO_DATE('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AND
    UFV.FCY_GKEY  IN (3575349497,3575349521,3334231702) AND
    RTVD.STATUS='COMPLETE'
    
    GROUP BY RTVD.GOS_TV_KEY,RTVD.ENTERED_YARD,RTVD.EXITED_YARD,ARLEN.ID,AREX.ID,RTVD.CREATOR,RTVD.SCALE_WEIGHT,RTVD.TRUCK_ID,RTVD.TRUCK_LICENSE_NBR,
    RCP.ID,RTVD.DRIVER_NAME,RTVD.DRIVER_LICENSE_NBR,RTVD.DRIVER_CARD_ID,RTVD.TRUCKING_CO_ID,RTVD.STATUS, 
    UT.ID, eqbo.nbr, ut.category, eqbo.HAS_REEFERS, UT.FREIGHT_KIND, ret.id, RE.RFR_TYPE, RTT.SUB_TYPE
) XX001
;