/*cv_gkey
(select * from  usrtosn4p.crg_bills_of_lading where nbr = b.nbr and COMPLEX_GKEY = U.COMPLEX_GKEY ) as "sss"
(select * from  USRTOSN4P.VSL_VESSEL_VISIT_DETAILS where VVD_GKEY = '3651480724') Vsd
--VESSEL_GKEY
(select * from  USRTOSN4P.VSL_VESSELS where  GKEY = '3628572715') vs,
(select * from  USRTOSN4P.VSL_VESSEL_CLASSES where GKEY = '3628570782') clase

--CLASE.GKEY, VS.GKEY , VSD.VVD_GKEY 

*/


SELECT Clase.ID, cbl.nbr ,CBL.COMPLEX_GKEY
FROM USRTOSN4P.VSL_VESSEL_CLASSES CLASE
LEFT JOIN USRTOSN4P.VSL_VESSELS              VS  ON CLASE.GKEY = VS.VESCLASS_GKEY 
LEFT JOIN USRTOSN4P.VSL_VESSEL_VISIT_DETAILS VSD ON VS.GKEY= vsd.vessel_gkey
LEFT JOIN USRTOSN4P.argo_carrier_visit       ACV ON VSD.VVD_GKEY = acv.cvcvd_gkey
LEFT JOIN USRTOSN4P.crg_bills_of_lading      CBL ON ACV.GKEY = CBL.CV_GKEY
;
WHERE cbl.nbr = 'HLCUSCL190513411';
--VS.GKEY = '3628572715';
--

HLCUBU3190400520

SELECT * FROM USRTOSN4P.VSL_VESSEL_VISIT_DETAILS;
SELECT * FROM USRTOSN4P.ARGO_CARRIER_VISIT;
 SELECT * FROM USRTOSN4P.INV_UNIT_FCY_VISIT;

SELECT ARRIVE_ORDER_ITEM_GKEY FROM USRTOSN4P.INV_UNIT
WHERE ARRIVE_ORDER_ITEM_GKEY = '3646453942';

SELECT * FROM USRTOSN4P.INV_UNIT_FCY_VISIT;


select * from USRTOSN4P.inv_eq_base_order
where nbr = 'HLCUBU3190400520' ;

