SELECT 
CHR(39) || U.ID || CHR(39) || ',' AS "N° Contenedor_Editado"

FROM USRTOSN4P.INV_UNIT U 
INNER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UF ON UF.UNIT_GKEY = U.GKEY
INNER JOIN USRTOSN4P.REF_EQUIPMENT RE                 ON U.ID = RE.ID_FULL
LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_TYPE RET               ON RET.GKEY =RE.EQTYP_GKEY
LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_TYPE ARQ               ON ARQ.GKEY = RET.ARCHETYPE
LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_GRADES REQ            ON REQ.GKEY = U.GRADE_GKEY
LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_CONDITIONS REC ON REC.GKEY = U.CONDITION_GKEY 
LEFT JOIN USRTOSN4P.INV_EQ_BASE_ORDER_ITEM EQBOI     ON U.DEPART_ORDER_ITEM_GKEY = EQBOI.GKEY
LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER EQBO           ON EQBO.GKEY = EQBOI.EQO_GKEY
LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER_ITEM EQBOIE ON U.ARRIVE_ORDER_ITEM_GKEY = EQBOIE.GKEY
LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER EQBOE  ON EQBOE.GKEY = EQBOIE.EQO_GKEY
LEFT OUTER JOIN USRTOSN4P.INV_GOODS GD                 ON U.GOODS = GD.GKEY
LEFT OUTER JOIN USRTOSN4P.CRG_BL_GOODS CBD             ON CBD.GDS_GKEY = GD.GKEY
LEFT OUTER JOIN USRTOSN4P.CRG_BILLS_OF_LADING BL       ON CBD.BL_GKEY = BL.GKEY
INNER JOIN USRTOSN4P.INV_EQ_STATE IES ON IES.EQ_GKEY = RE.GKEY
INNER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED BSO     ON BSO.GKEY = IES.EQ_OWNER_GKEY AND BSO.ROLE = 'LINEOP'
INNER JOIN USRTOSN4P.ARGO_FACILITY FCY ON FCY.GKEY = UF.FCY_GKEY
LEFT OUTER JOIN USRTOSN4P.ARGO_CARRIER_VISIT CV        ON (CV.GKEY = EQBOE.VESSEL_VISIT_GKEY OR CV.GKEY = BL.CV_GKEY)
LEFT OUTER JOIN USRTOSN4P.VSL_VESSEL_VISIT_DETAILS VVD ON VVD.VVD_GKEY = CV.CVCVD_GKEY
LEFT OUTER JOIN USRTOSN4P.VSL_VESSELS VS               ON VS.GKEY = VVD.VESSEL_GKEY
LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED BSA       ON (BSA.GKEY = EQBOE.AGENT_GKEY AND BSA.ROLE = 'AGENT')
LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED BSL       ON (BSL.GKEY = U.LINE_OP AND BSL.ROLE = 'LINEOP')
WHERE U.FREIGHT_KIND = 'MTY' AND UF.TRANSIT_STATE = 'S40_YARD' AND U.COMPLEX_GKEY = 3575349411
AND (BL.NBR IS NULL OR (BL.NBR = GD.BL_NBR OR BL.NBR = SUBSTR(GD.BL_NBR,0,LENGTH(GD.BL_NBR)-1)))
AND FCY.ID = NVL('VNT',FCY.ID )
--AND BSL.ID = NVL('HLC',BSL.ID )
;
