/*==============  STOCK  PIL ==============================*/
SELECT DISTINCT
U.ID                                    														AS "EQUIPAMIENTO",
SUBSTR(ARQ.id,1,2)                          													AS "TAMAÑO",
SUBSTR(ARQ.id,3,2)                          													AS "TIPO",
re.safe_kg - re.tare_kg        																	AS "PMM",
REC.ID                                  														AS "CODIGO STATUS CAJA",
egr.ID                                  														AS "CLASE",
BS.ID 																							AS "CLIENTE",
U.CUSTDFF_FLEX_STRING10                                                                         AS "COSTO CLIENTE",
U.CUSTDFF_FLEX_STRING09                                                                         AS "COSTO LINEA",
SUBSTR(CUSTDFF_FLEX_STRING15,LENGTH(CUSTDFF_FLEX_STRING15) - 8, LENGTH(CUSTDFF_FLEX_STRING15))  AS "FECHA ACEPTACION CAJA",
SUBSTR(CUSTDFF_FLEX_STRING15,1, LENGTH(CUSTDFF_FLEX_STRING15) - 10) 							AS "TOTAL CAJA",
CASE WHEN U.FLEX_STRING08 = 'A' THEN 'APERTURA'
     WHEN U.FLEX_STRING08 = 'D' THEN 'DESCARGA'
     WHEN U.FLEX_STRING08 = 'E' THEN 'DEVOLUCIO EXP'
     WHEN U.FLEX_STRING08 = 'M' THEN 'MANUALES'
     WHEN U.FLEX_STRING08 = 'P' THEN 'PARTICULARES'  END                                        AS "TIPO ENTRADA",
TO_CHAR(ufv.TIME_IN,'YYYY-MM-DD HH24:MI') 														AS "F ENTRADA STOCK" ,
TRUNC(NVL(TRUNC(ufv.time_out),CURRENT_DATE) - TRUNC(ufv.time_in)) 								AS "DIAS ENTRADA STOCK",
u.custdff_flex_string12                     													AS "MOTIVO BLOQUEO",
U.remark                                    													AS "NOTAS1",
u.custdff_flex_string11                     													AS "NOTAS2",
NVL(u.custdff_flex_string14,EQBO.NBR)       													AS "BOOKING RESERVA PTE"

FROM            	USRTOSN4P.INV_UNIT 						U
LEFT OUTER JOIN 	USRTOSN4P.INV_UNIT_FCY_VISIT 			UFV     ON U.GKEY = UFV.UNIT_GKEY
LEFT OUTER JOIN 	USRTOSN4P.REF_BIZUNIT_SCOPED 			BS      ON U.LINE_OP = BS.GKEY  AND BS.ROLE = 'LINEOP'
LEFT OUTER JOIN 	USRTOSN4P.INV_EQ_BASE_ORDER_ITEM 		EQBOI 	ON U.DEPART_ORDER_ITEM_GKEY = EQBOI.GKEY
LEFT OUTER JOIN 	USRTOSN4P.INV_EQ_BASE_ORDER 			EQBO 	ON EQBO.GKEY = EQBOI.EQO_GKEY AND EQBO.SUB_TYPE = 'EDO'
LEFT OUTER JOIN 	USRTOSN4P.REF_EQUIPMENT 				RE      ON U.ID = RE.ID_FULL
LEFT OUTER JOIN 	USRTOSN4P.REF_EQUIP_TYPE 				RET     ON RET.GKEY =RE.EQTYP_GKEY
LEFT OUTER JOIN 	USRTOSN4P.REF_EQUIP_TYPE 				ARQ     ON ARQ.GKEY = RET.ARCHETYPE
LEFT OUTER JOIN 	USRTOSN4P.ARGO_CARRIER_VISIT 			CV      ON CV.GKEY = EQBO.VESSEL_VISIT_GKEY
LEFT OUTER JOIN 	USRTOSN4P.VSL_VESSEL_VISIT_DETAILS 		VVD 	ON VVD.VVD_GKEY = CV.CVCVD_GKEY
LEFT OUTER JOIN 	USRTOSN4P.VSL_VESSELS 					VS      ON VS.GKEY = VVD.VESSEL_GKEY
LEFT OUTER JOIN 	USRTOSN4P.SRV_EVENT 					EV      ON EV.APPLIED_TO_GKEY = EQBO.GKEY
LEFT OUTER JOIN 	USRTOSN4P.REF_BIZUNIT_SCOPED 			BSA     ON BSA.GKEY = EQBO.AGENT_GKEY AND BSA.ROLE = 'AGENT'
LEFT OUTER JOIN 	USRTOSN4P.REF_ROUTING_POINT 			RP      ON RP.GKEY =  EQBO.CUSTDFF_EDO_FLEX_STRING20
LEFT OUTER JOIN 	USRTOSN4P.REF_EQUIP_CONDITIONS 			REC 	ON REC.GKEY = U.CONDITION_GKEY
LEFT OUTER JOIN 	USRTOSN4P.ORD_EQUIPMENT_ORDER_ITEMS     ITEM    ON U.DEPART_ORDER_ITEM_GKEY = ITEM.GKEY
LEFT OUTER JOIN 	USRTOSN4P.REF_EQUIP_GRADES              EGR     ON EGR.gkey = U.GRADE_GKEY
LEFT OUTER JOIN 	USRTOSN4P.ARGO_FACILITY                 AF      ON AF.GKEY = UFV.FCY_GKEY
WHERE  
		BS.ID='PIL'
		AND UFV.TRANSIT_STATE LIKE '%YARD%'
		AND U.FREIGHT_KIND = 'MTY'
		AND AF.ID = 'VNT'
        --$P{FACILITY};
        ;
        
        