SELECT 
CASE FCY.ID
WHEN 'ARG' THEN 'Callao'
WHEN 'VNT' THEN 'Gambetta 1'
WHEN 'GT2' THEN 'Gambetta 2'
END
AS "Depot",
U.ID AS "N° Contenedor",
--CHR(39) || U.ID || CHR(39) || ',' AS "N° Contenedor_Editado",
CASE RET.NOMINAL_LENGTH WHEN 'NOM40' THEN '40' ELSE
CASE RET.NOMINAL_LENGTH WHEN 'NOM45' THEN '45' ELSE
CASE RET.NOMINAL_LENGTH WHEN 'NOM20' THEN '20' ELSE
RET.NOMINAL_LENGTH
END END END AS "Tamaño",
CASE WHEN (RET.ID = '22P1' OR RET.ID = '42P3') THEN 'FR'    ELSE
CASE WHEN (RET.ID = 'L5G1' OR RET.ID = '45RH' OR RET.ID = '25R1') THEN 'RH'  ELSE
CASE WHEN (RET.ID = '42P1' OR RET.ID = '22P0') THEN 'FL'     ELSE
CASE WHEN (RET.ID = 'L5R1' OR RET.ID = '45RH' OR RET.ID = '25R1') THEN 'RH' ELSE
CASE WHEN (RET.ID = '22B0') THEN 'BL' ELSE
CASE WHEN (RET.ID = '45P3' ) THEN 'FH'   ELSE
CASE WHEN (RET.ID = 'L5G1' ) THEN 'HC' ELSE
CASE WHEN (RET.ID = '42V0' ) THEN 'HV' ELSE
CASE WHEN (RET.ID = '25U1' ) THEN 'OH' ELSE
CASE WHEN (RET.ID = '22P5') THEN 'OS' ELSE
CASE WHEN (RET.ID = '42R0') THEN 'R1' ELSE
CASE WHEN (RET.ID = '22R0') THEN 'RC' ELSE
CASE WHEN (RET.ID = '42R0') THEN 'RF' ELSE
CASE WHEN (RET.ID = '28U1') THEN 'TS'  ELSE
CASE WHEN (RET.ID = '22V0') THEN 'VH'  ELSE
CASE WHEN arq.ID = '20DR' THEN 'ST'  ELSE
CASE WHEN arq.ID = '20OT' THEN  'OT' ELSE
CASE WHEN arq.ID = '20RF' THEN 'RF'  ELSE
CASE WHEN arq.ID = '20TK' THEN 'TK'  ELSE
CASE WHEN arq.ID = '40DR' THEN 'ST' ELSE
CASE WHEN arq.ID = '40HC' THEN 'HC'  ELSE
CASE WHEN arq.ID = '40OT' THEN 'OT'  ELSE
CASE WHEN arq.ID = '40PL' THEN 'PL' ELSE
CASE WHEN arq.ID = '40RH' THEN 'RH' ELSE
CASE WHEN arq.ID = '40TK' THEN 'TK' ELSE
CASE WHEN arq.ID = 'L500' THEN 'TK' ELSE
CASE WHEN arq.ID = '2500' THEN 'HC' ELSE ARQ.ID
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END AS "Tipo",
RET.ID AS "ISO",
RE.TARE_KG AS "Tara",
CASE WHEN RE.SAFE_KG = 0 THEN 
''ELSE
TO_CHAR(RE.SAFE_KG - RE.TARE_KG) END  AS "Payload",
TO_CHAR(RE.BUILD_DATE, 'MM/YYYY') AS "Fecha de Fabricación",
BSO.ID AS "Linea Naviera",
REQ.ID AS "Clase",
REC.ID AS "Condición Caja",
REC.DESCRIPTION AS "Desc. Condicion Caja",
CASE WHEN U.FLEX_STRING08 = 'A' THEN 
'Apertura'
WHEN U.FLEX_STRING08 = 'P' THEN 
'Particular' 
WHEN U.FLEX_STRING08 = 'D' THEN
'Descarga'
WHEN U.FLEX_STRING08 = 'E' THEN
'Devolución Exp'
WHEN U.FLEX_STRING08 = 'M' THEN
'Manuales'
END
AS "Tipo de Entrada",
TO_CHAR(VVD.PUBLISHED_ETA,'DD/MM/YYYY')AS "Fecha ETA",
VS.NAME AS "Nave",
VVD.IB_VYG AS "Viaje",
CASE WHEN (EQBOE.NBR IS NOT NULL) THEN 
EQBOE.NBR
WHEN GD.BL_NBR = BL.NBR THEN GD.BL_NBR ELSE
SUBSTR(GD.BL_NBR,0,LENGTH(GD.BL_NBR)-1)
END
AS
"B/L",
BSA.NAME AS "Cliente",
TO_CHAR( UF.TIME_RND,'DD/MM/YYYY')AS "Fecha Ingreso Depot",
(TRUNC(SYSDATE) - TRUNC(UF.TIME_RND)) AS "Overdue/Dias en Stock",
U.CUSTDFF_FLEX_STRING13 AS "Referencia Ejecutivo/Asignador",
U.CUSTDFF_FLEX_STRING12 AS "Motivo de Bloqueo",
U.REMARK AS "Notas",
EQBO.NBR AS "Booking",
UF.FLEX_STRING07 AS "Nep - Booking Llenado",
TO_CHAR(TO_DATE(SUBSTR(U.CUSTDFF_FLEX_STRING15,INSTR(U.CUSTDFF_FLEX_STRING15,'/')+1)),'DD/MM/YYYY') AS "Fecha Aprobacion Caja",
TO_CHAR(U.CUSTDFF_FLEX_DATE03,'DD/MM/YYYY') AS "Fecha Reparación Caja",
U.CUSTDFF_FLEX_STRING14 AS "Booking Pre-Asignacion",
U.CUSTDFF_FLEX_STRING10 AS "Costo Rep Cliente",
U.CUSTDFF_FLEX_STRING09 AS "Costo Rep Línea",
TRIM(SUBSTR(U.CUSTDFF_FLEX_STRING15,0,INSTR(U.CUSTDFF_FLEX_STRING15,'/')-1)) AS "Total Caja",
TO_CHAR(U.CUSTDFF_FLEX_DATE02,'DD/MM/YYYY') AS "Fecha Termino Lavado"
FROM USRTOSN4P.INV_UNIT U 
INNER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UF ON UF.UNIT_GKEY = U.GKEY
INNER JOIN USRTOSN4P.REF_EQUIPMENT RE                 ON U.ID = RE.ID_FULL
LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_TYPE RET               ON RET.GKEY =RE.EQTYP_GKEY
LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_TYPE ARQ               ON ARQ.GKEY = RET.ARCHETYPE
LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_GRADES REQ            ON REQ.GKEY = U.GRADE_GKEY
LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_CONDITIONS REC ON REC.GKEY = U.CONDITION_GKEY 
LEFT JOIN USRTOSN4P.INV_EQ_BASE_ORDER_ITEM EQBOI     ON U.DEPART_ORDER_ITEM_GKEY = EQBOI.GKEY
LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER EQBO           ON EQBO.GKEY = EQBOI.EQO_GKEY
LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER_ITEM EQBOIE ON U.ARRIVE_ORDER_ITEM_GKEY = EQBOIE.GKEY
LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER EQBOE  ON EQBOE.GKEY = EQBOIE.EQO_GKEY
LEFT OUTER JOIN USRTOSN4P.INV_GOODS GD                 ON U.GOODS = GD.GKEY
LEFT OUTER JOIN USRTOSN4P.CRG_BL_GOODS CBD             ON CBD.GDS_GKEY = GD.GKEY
LEFT OUTER JOIN USRTOSN4P.CRG_BILLS_OF_LADING BL       ON CBD.BL_GKEY = BL.GKEY
INNER JOIN USRTOSN4P.INV_EQ_STATE IES ON IES.EQ_GKEY = RE.GKEY
INNER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED BSO     ON BSO.GKEY = IES.EQ_OWNER_GKEY AND BSO.ROLE = 'LINEOP'
INNER JOIN USRTOSN4P.ARGO_FACILITY FCY ON FCY.GKEY = UF.FCY_GKEY
LEFT OUTER JOIN USRTOSN4P.ARGO_CARRIER_VISIT CV        ON (CV.GKEY = EQBOE.VESSEL_VISIT_GKEY OR CV.GKEY = BL.CV_GKEY)
LEFT OUTER JOIN USRTOSN4P.VSL_VESSEL_VISIT_DETAILS VVD ON VVD.VVD_GKEY = CV.CVCVD_GKEY
LEFT OUTER JOIN USRTOSN4P.VSL_VESSELS VS               ON VS.GKEY = VVD.VESSEL_GKEY
LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED BSA       ON (BSA.GKEY = EQBOE.AGENT_GKEY AND BSA.ROLE = 'AGENT')
LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED BSL       ON (BSL.GKEY = U.LINE_OP AND BSL.ROLE = 'LINEOP')
WHERE U.FREIGHT_KIND = 'MTY' AND UF.TRANSIT_STATE = 'S40_YARD' AND U.COMPLEX_GKEY = 3575349411
AND (BL.NBR IS NULL OR (BL.NBR = GD.BL_NBR OR BL.NBR = SUBSTR(GD.BL_NBR,0,LENGTH(GD.BL_NBR)-1)))
AND FCY.ID = NVL('VNT',FCY.ID )
--AND BSL.ID = NVL('HLC',BSL.ID )
;
