/*============== STOCK  HLC==============================*/
SELECT
DISTINCT
U.ID                                        AS "EQUIPAMIENTO",
SUBSTR(ARQ.id,3,2)                          AS "TIPO",
SUBSTR(ARQ.id,1,2)                          AS "TAMAÑO",
re.tare_kg                                  AS "TARA",
re.safe_kg - re.tare_kg                    AS "PMM",
egr.ID                                      AS "CLASE",
REC.ID                                      AS "CODIGO STATUS CAJA",
TO_CHAR(ufv.TIME_IN,'YYYY-MM-DD HH24:MI')   AS "F ENTRADA STOCK" ,
TRUNC(NVL(TRUNC(ufv.time_out),CURRENT_DATE) - TRUNC(ufv.time_in)) AS "DIAS ENTRADA STOCK",
RE.build_date                               as "FECHA FABRICACION",
u.custdff_flex_string12                     AS "MOTIVO BLOQUEO",
NVL(u.custdff_flex_string14,EQBO.NBR)       AS "BOOKING RESERVA PTE",
SUBSTR(CUSTDFF_FLEX_STRING15,LENGTH(CUSTDFF_FLEX_STRING15) - 8, LENGTH(CUSTDFF_FLEX_STRING15))  AS "FECHA ACEPTACION CAJA",
u.CUSTDFF_FLEX_DATE03                       AS "FECHA FIN REPARACION",
U.remark                                    as "NOTA1",
u.custdff_flex_string11                     as "NOTA2",
BS.ID AS "LINEA",
SUBSTR(CUSTDFF_FLEX_STRING15,1, LENGTH(CUSTDFF_FLEX_STRING15) - 10) AS "TOTAL CAJA"

FROM            USRTOSN4P.INV_UNIT U
LEFT OUTER JOIN USRTOSN4P.INV_UNIT_FCY_VISIT UFV       ON U.GKEY = UFV.UNIT_GKEY
LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED BS        ON U.LINE_OP = BS.GKEY  AND BS.ROLE = 'LINEOP'

LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER_ITEM EQBOI ON U.DEPART_ORDER_ITEM_GKEY = EQBOI.GKEY

LEFT OUTER JOIN USRTOSN4P.INV_EQ_BASE_ORDER EQBO       ON EQBO.GKEY = EQBOI.EQO_GKEY AND EQBO.SUB_TYPE = 'EDO'
LEFT OUTER JOIN USRTOSN4P.REF_EQUIPMENT RE             ON U.ID = RE.ID_FULL
LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_TYPE RET           ON RET.GKEY =RE.EQTYP_GKEY
LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_TYPE ARQ           ON ARQ.GKEY = RET.ARCHETYPE
LEFT OUTER JOIN USRTOSN4P.ARGO_CARRIER_VISIT CV        ON CV.GKEY = EQBO.VESSEL_VISIT_GKEY
LEFT OUTER JOIN USRTOSN4P.VSL_VESSEL_VISIT_DETAILS VVD ON VVD.VVD_GKEY = CV.CVCVD_GKEY
LEFT OUTER JOIN USRTOSN4P.VSL_VESSELS VS               ON VS.GKEY = VVD.VESSEL_GKEY
LEFT OUTER JOIN USRTOSN4P.SRV_EVENT EV                 ON EV.APPLIED_TO_GKEY = EQBO.GKEY
LEFT OUTER JOIN USRTOSN4P.REF_BIZUNIT_SCOPED BSA       ON BSA.GKEY = EQBO.AGENT_GKEY AND BSA.ROLE = 'AGENT'
LEFT OUTER JOIN USRTOSN4P.REF_ROUTING_POINT RP         ON RP.GKEY =  EQBO.CUSTDFF_EDO_FLEX_STRING20
LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_CONDITIONS REC     ON REC.GKEY = U.CONDITION_GKEY
LEFT OUTER JOIN USRTOSN4P.ORD_EQUIPMENT_ORDER_ITEMS     ITEM        ON U.DEPART_ORDER_ITEM_GKEY = ITEM.GKEY
LEFT OUTER JOIN USRTOSN4P.REF_EQUIP_GRADES              EGR         ON EGR.gkey = U.GRADE_GKEY
LEFT OUTER JOIN USRTOSN4P.ARGO_FACILITY                 AF          ON AF.GKEY = UFV.FCY_GKEY

WHERE  
BS.ID='HLC'
AND UFV.TRANSIT_STATE LIKE '%YARD%'
AND U.FREIGHT_KIND = 'MTY'
AND AF.ID = 'VNT';



--AND VVD.PUBLISHED_ETA < TO_DATE('2019-12-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') 
--AND VVD.PUBLISHED_ETA > TO_DATE('2019-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') ;
--AND u.custdff_flex_string14 IS NOT NULL;
--AND VVD.PUBLISHED_ETA < TO_DATE($P{fechaETAFin},'YYYY/MM/DD HH24:MI')
--AND VVD.PUBLISHED_ETA > TO_DATE($P{fechaETAInicio},'YYYY/MM/DD HH24:MI')

SELECT * FROM USRTOSN4P.REF_EQUIP_GRADES
--ord_ar_equipment_order_items
WHERE   
--EQ_GRADE_ID IS NOT NULL;
ROWNUM <= 100;
ord_equipment_order_items;

select ID from ARGO_FACILITY;


select u.grade_gkey, u.* from USRTOSN4P.INV_UNIT u
where rownum<=100;

